// Generated by backend/seed_reviews.py. Synthetic examples for every month of 2026,
// including future months. Only used until a populated backend store is available.
const DEMO_REVIEWS = [
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-01-05",
    "favorite": "Mwongoza watalii alikuwa mwenye urafiki na maarifa mengi.",
    "improvement": "Ziara ingeweza kujumuisha mapumziko mafupi.",
    "original_favorite": "The guide was friendly and very knowledgeable.",
    "original_improvement": "The tour could include a short rest break.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-01-08",
    "favorite": "Nilifurahia kujifunza historia ya mji wa kale.",
    "improvement": "Kundi lilikuwa kubwa kidogo.",
    "original_favorite": "I loved learning about the history of the old town.",
    "original_improvement": "The group was a little too large.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-01-12",
    "favorite": "Mandhari kutoka sehemu ya kutazamia yalikuwa ya kuvutia sana.",
    "improvement": "Muda zaidi wa kupiga picha ungekuwa mzuri.",
    "original_favorite": "The views from the lookout were incredible.",
    "original_improvement": "More time for photos would be helpful.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-01-16",
    "favorite": "Vyakula vya wenyeji tulivyoonja vilikuwa vitamu.",
    "improvement": "Sehemu ya kukutana ilikuwa ngumu kuipata.",
    "original_favorite": "The local food tasting was delicious.",
    "original_improvement": "The meeting point was difficult to find.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-01-20",
    "favorite": "Mwongoza watalii alisimulia hadithi za kuvutia kuhusu jamii.",
    "improvement": "Ziara inapaswa kuanza mapema kidogo.",
    "original_favorite": "The guide shared fascinating stories about the community.",
    "original_improvement": "The tour should start a little earlier.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-01-24",
    "favorite": "Njia ya matembezi ilituonyesha maeneo ambayo tusingeyapata wenyewe.",
    "improvement": "Tafadhali tupatie maelezo ya njia kabla ya ziara.",
    "original_favorite": "The walking route showed us places we would not have found alone.",
    "original_improvement": "Please provide the route details before the tour.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-01-29",
    "favorite": "Nilifurahia kukutana na wasanii wa eneo hilo sokoni.",
    "improvement": "Sauti ya mfumo wa sauti ingeweza kuongezwa.",
    "original_favorite": "I enjoyed meeting local artists at the market.",
    "original_improvement": "The audio system could be louder.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-02-02",
    "favorite": "Vitu vilivyoonyeshwa katika jumba la makumbusho vilivutia.",
    "improvement": "Ziara iliharakishwa na ilianza kuchelewa.",
    "original_favorite": "The museum collection was interesting.",
    "original_improvement": "The tour felt rushed and started late.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-02-06",
    "favorite": "Mwongoza watalii wetu aliifanya ziara nzima iwafurahishe watoto.",
    "improvement": "Punguzo kwa familia lingependeza.",
    "original_favorite": "Our guide made the entire experience fun for the children.",
    "original_improvement": "A family discount would be appreciated.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-02-10",
    "favorite": "Mandhari ya jua likitua juu ya mto yalikuwa mazuri.",
    "improvement": "Maelekezo kuhusu sehemu ya kuchukuliwa na usafiri yawe wazi zaidi.",
    "original_favorite": "The sunset over the river was beautiful.",
    "original_improvement": "The transport pickup instructions could be clearer.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-02-14",
    "favorite": "Onyesho la upishi lilitushirikisha na lilivutia.",
    "improvement": "Ningependa kupewa maelekezo ya mapishi yaliyochapishwa.",
    "original_favorite": "The cooking demonstration was personal and engaging.",
    "original_improvement": "I would have liked a printed recipe.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-02-18",
    "favorite": "Maelezo kuhusu utamaduni yalitolewa kwa makini.",
    "improvement": "Kunapaswa kuwa na sehemu zaidi za kukaa njiani.",
    "original_favorite": "The cultural explanations were thoughtful.",
    "original_improvement": "There should be more seating along the route.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-02-22",
    "favorite": "Matembezi ya kutazama wanyamapori yalituwezesha kuona wanyama wengi.",
    "improvement": "Kila mgeni anapaswa kupewa darubini.",
    "original_favorite": "The wildlife walk gave us several great sightings.",
    "original_improvement": "Binoculars should be available for every guest.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-02-26",
    "favorite": "Mwongoza watalii alijibu kila swali kwa uvumilivu.",
    "improvement": "Hakuna jambo kubwa linalohitaji kuboreshwa.",
    "original_favorite": "The guide answered every question with patience.",
    "original_improvement": "Nothing major needs improvement.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-03-01",
    "favorite": "Ziara ya majengo ilikuwa na maelezo mengi na ilipangwa vizuri.",
    "improvement": "Ramani ya njia ingekuwa na manufaa.",
    "original_favorite": "The architecture tour was informative and well organized.",
    "original_improvement": "A map of the route would be useful.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-03-05",
    "favorite": "Matembezi ya kuelekea maporomoko ya maji yalikuwa magumu lakini yalifurahisha.",
    "improvement": "Tafadhali elezeni kwa uwazi zaidi kiwango cha ugumu wa matembezi.",
    "original_favorite": "The waterfall hike was challenging but rewarding.",
    "original_improvement": "Please describe the hike difficulty more clearly.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-03-09",
    "favorite": "Nilifurahia kutembelea bustani ya jamii.",
    "improvement": "Ziara ilihitaji mpangilio bora kati ya vituo.",
    "original_favorite": "I enjoyed the visit to the community garden.",
    "original_improvement": "The tour needed better organization between stops.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-03-13",
    "favorite": "Onyesho la muziki lilikuwa jambo bora zaidi jioni yetu.",
    "improvement": "Mpangilio wa viti ungeweza kuwa wa kustarehesha zaidi.",
    "original_favorite": "The music performance was the highlight of our evening.",
    "original_improvement": "The seating arrangement could be more comfortable.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-03-17",
    "favorite": "Mwongoza watalii alitukaribisha vizuri na alitufanya tujisikie salama.",
    "improvement": "Maelezo mafupi kuhusu usalama mwanzoni yangesaidia.",
    "original_favorite": "The guide was welcoming and made us feel safe.",
    "original_improvement": "Adding a brief introduction about safety would help.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-03-21",
    "favorite": "Ziara ya soko ilitupa nafasi nzuri ya kujionea maisha ya wenyeji.",
    "improvement": "Chaguo zaidi za vyakula visivyo na nyama zingekuwa nzuri.",
    "original_favorite": "The market tour gave us a great taste of local life.",
    "original_improvement": "More vegetarian tasting options would be nice.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-03-25",
    "favorite": "Sehemu za kusimama kupiga picha zilichaguliwa vizuri sana.",
    "improvement": "Ziara ingeweza kutoa huduma ya mpiga picha mtaalamu.",
    "original_favorite": "The photography stops were perfectly chosen.",
    "original_improvement": "The tour could offer a professional photography option.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-03-29",
    "favorite": "Jengo la kihistoria lilivutia sana.",
    "improvement": "Mwongoza watalii anapaswa kuzungumza polepole na kutumia kipaza sauti.",
    "original_favorite": "The historic building was impressive.",
    "original_improvement": "The guide should speak more slowly and use a microphone.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-04-02",
    "favorite": "Nilipenda jinsi kundi letu lilivyokuwa dogo.",
    "improvement": "Barua pepe ya uthibitisho inapaswa kujumuisha maelezo ya maegesho.",
    "original_favorite": "I appreciated the small group size.",
    "original_improvement": "The confirmation email should include parking information.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-04-06",
    "favorite": "Safari ya mashua mtoni ilikuwa ya kustarehesha na yenye mandhari mazuri.",
    "improvement": "Sehemu zaidi za kivuli kwenye mashua zingesaidia.",
    "original_favorite": "The river cruise was relaxing and scenic.",
    "original_improvement": "A few more shade areas on the boat would be helpful.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-04-10",
    "favorite": "Warsha ya ufundi ilikuwa ya ubunifu na ya kufurahisha.",
    "improvement": "Vifaa viliisha kabla ya kila mtu kumaliza.",
    "original_favorite": "The craft workshop was creative and enjoyable.",
    "original_improvement": "The materials ran out before everyone finished.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-04-14",
    "favorite": "Historia ya eneo hilo ilisimuliwa kwa njia ya kuvutia.",
    "improvement": "Ziara inapaswa kujumuisha picha zaidi za kihistoria.",
    "original_favorite": "The neighborhood history was presented in an engaging way.",
    "original_improvement": "The tour should include more historical photographs.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-04-18",
    "favorite": "Ufukwe ulikuwa mtulivu na mwongoza watalii alikuwa bora sana.",
    "improvement": "Tafadhali toeni chupa za maji zinazoweza kutumika tena.",
    "original_favorite": "The beach was peaceful and the guide was excellent.",
    "original_improvement": "Please provide reusable water bottles.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-04-22",
    "favorite": "Bustani ya mimea ilikuwa na aina nyingi za mimea ya kuvutia.",
    "improvement": "Majina ya mimea yangeweza kuonyeshwa kwa uwazi zaidi.",
    "original_favorite": "The botanical garden had an amazing variety of plants.",
    "original_improvement": "The plant names could be displayed more clearly.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-04-26",
    "favorite": "Usimulizi wa hadithi ulifanya masimulizi ya kale yaonekane halisi.",
    "improvement": "Kijitabu kifupi cha hadithi kingekuwa kumbukumbu nzuri.",
    "original_favorite": "The storytelling made the legends feel alive.",
    "original_improvement": "A short booklet with the stories would be a great souvenir.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-04-30",
    "favorite": "Vitafunio vya wenyeji vilikuwa sehemu niliyoipenda zaidi.",
    "improvement": "Ziara inapaswa kutoa muda zaidi katika vituo vya chakula.",
    "original_favorite": "The local snacks were my favorite part.",
    "original_improvement": "The tour should have more time at the food stops.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-05-04",
    "favorite": "Njia ya baiskeli ilikuwa na mandhari mazuri na ilifurahisha.",
    "improvement": "Baiskeli zinahitaji viti vya kustarehesha zaidi.",
    "original_favorite": "The cycling route was scenic and enjoyable.",
    "original_improvement": "The bicycles need more comfortable seats.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-05-08",
    "favorite": "Mwongoza watalii alitupa mapendekezo mazuri kwa sehemu iliyobaki ya safari yetu.",
    "improvement": "Orodha ya mapendekezo baada ya ziara ingekuwa na manufaa.",
    "original_favorite": "The guide gave excellent recommendations for the rest of our trip.",
    "original_improvement": "A list of recommendations would be useful afterward.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-05-12",
    "favorite": "Maeneo madogo ya kihistoria yalikuwa hazina zilizofichika.",
    "improvement": "Njia inapaswa kujumuisha mapumziko zaidi ya kutumia vyoo.",
    "original_favorite": "The small historical sites were hidden gems.",
    "original_improvement": "The route should include more restroom breaks.",
    "is_demo": true
  },
  {
    "rating": 1,
    "language": "sw",
    "date": "2026-05-16",
    "favorite": "Mandhari katika kituo cha mwisho cha kutazamia yalikuwa mazuri.",
    "improvement": "Ziara ilifutwa dakika za mwisho na ile mbadala ilipangwa vibaya.",
    "original_favorite": "The final viewpoint was beautiful.",
    "original_improvement": "The tour was canceled late and the replacement was poorly organized.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-05-20",
    "favorite": "Wanajamii walikuwa wakarimu na wenye ukarimu kwa wageni.",
    "improvement": "Ningefurahia mazungumzo marefu zaidi na wenyeji.",
    "original_favorite": "The community members were generous and welcoming.",
    "original_improvement": "I would enjoy a longer conversation with the hosts.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-05-24",
    "favorite": "Kipindi cha kupiga picha wakati wa machweo kilikuwa cha kukumbukwa.",
    "improvement": "Tafadhali tutumieni taarifa za hali ya hewa kabla ya kipindi hicho.",
    "original_favorite": "The sunset photography session was memorable.",
    "original_improvement": "Please send weather updates before the session.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-05-28",
    "favorite": "Mwongoza watalii alikuwa mcheshi sana.",
    "improvement": "Ratiba ya safari inapaswa kuelezwa mwanzoni.",
    "original_favorite": "The guide had a great sense of humor.",
    "original_improvement": "The itinerary should be shared at the beginning.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-06-01",
    "favorite": "Ziara ilitupa uhusiano wa maana na utamaduni wa wenyeji.",
    "improvement": "Tafadhali pangeni ziara hii katika siku zaidi.",
    "original_favorite": "The tour gave us a meaningful connection to the local culture.",
    "original_improvement": "Please offer this experience on more days.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-06-05",
    "favorite": "Matembezi msituni yalikuwa ya utulivu na yenye mandhari mazuri.",
    "improvement": "Maelezo zaidi kuhusu mimea ya eneo hilo yangependeza.",
    "original_favorite": "The forest walk was calm and beautiful.",
    "original_improvement": "More information about the local plants would be welcome.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-06-09",
    "favorite": "Mwongoza watalii alikumbuka jina la kila mtu na aliunganisha kundi vizuri.",
    "improvement": "Utaratibu wa kujiandikisha ungeweza kuwa wa haraka zaidi.",
    "original_favorite": "The guide remembered everyone's name and made the group feel connected.",
    "original_improvement": "The check-in process could be faster.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-06-13",
    "favorite": "Onyesho la ngoma za jadi lilikuwa lenye nguvu na la kusisimua.",
    "improvement": "Mwonekano kutoka sehemu ya nyuma ya ukumbi ungeweza kuboreshwa.",
    "original_favorite": "The traditional dance performance was vibrant and exciting.",
    "original_improvement": "The venue could have better visibility from the back.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-06-17",
    "favorite": "Safari ya mashua ilitupa mandhari tofauti ya jiji.",
    "improvement": "Injini ya mashua ilikuwa na kelele wakati maelezo yalipotolewa.",
    "original_favorite": "The boat ride offered a different view of the city.",
    "original_improvement": "The boat engine was noisy during the explanations.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-06-21",
    "favorite": "Ziara ilikuwa rahisi kufikiwa na wafanyakazi walijali mahitaji yetu.",
    "improvement": "Tafadhali chapisheni maelezo ya ufikivu mapema.",
    "original_favorite": "The tour was accessible and the staff were considerate.",
    "original_improvement": "Please publish accessibility details in advance.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-06-25",
    "favorite": "Zawadi iliyotengenezwa kwa mikono ilikuwa kumbukumbu nzuri ya ziara.",
    "improvement": "Miundo zaidi ya zawadi za kumbukumbu ingependeza.",
    "original_favorite": "The handmade souvenir was a lovely reminder of the visit.",
    "original_improvement": "More souvenir designs would be interesting.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-06-29",
    "favorite": "Kila kituo kilivutia na kasi ya ziara ilikuwa nzuri sana.",
    "improvement": "Ziara ilikuwa nzuri sana ilivyokuwa.",
    "original_favorite": "Every stop was interesting and the pacing was excellent.",
    "original_improvement": "The tour was excellent as it was.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-07-03",
    "favorite": "Mwongoza watalii alieleza mila kwa heshima.",
    "improvement": "Kipeperushi chenye tafsiri kingewasaidia wageni wa kimataifa.",
    "original_favorite": "The guide explained the traditions respectfully.",
    "original_improvement": "A translation handout would help international visitors.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-07-07",
    "favorite": "Mazingira ya jioni na muziki wa moja kwa moja vilikuwa vizuri sana.",
    "improvement": "Hafla ingeweza kuwa na meza zaidi.",
    "original_favorite": "The evening atmosphere and live music were wonderful.",
    "original_improvement": "The event could include a few more tables.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-07-11",
    "favorite": "Eneo tulilofika lilistahili kutembelewa.",
    "improvement": "Ratiba ilibadilishwa bila taarifa ya kutosha.",
    "original_favorite": "The destination itself was worth visiting.",
    "original_improvement": "The schedule changed without enough notice.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-07-15",
    "favorite": "Mwongoza watalii alitupa maelezo ya kina kuhusu mfumo wa ikolojia wa eneo hilo.",
    "improvement": "Njia ingeweza kuwa na alama zilizo wazi zaidi.",
    "original_favorite": "The guide gave us a detailed explanation of the local ecosystem.",
    "original_improvement": "The route could have clearer signs.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-07-19",
    "favorite": "Ziara ilitupa uzoefu halisi wa maisha ya wenyeji.",
    "improvement": "Ningependa chaguo la kundi dogo zaidi.",
    "original_favorite": "The experience felt authentic rather than touristy.",
    "original_improvement": "I would love an option for an even smaller group.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-01-01",
    "favorite": "Mwongoza watalii alikuwa mwenye urafiki na maarifa mengi.",
    "improvement": "Ziara ingeweza kujumuisha mapumziko mafupi.",
    "original_favorite": "The guide was friendly and very knowledgeable.",
    "original_improvement": "The tour could include a short rest break.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-01-03",
    "favorite": "Vitu vilivyoonyeshwa katika jumba la makumbusho vilivutia.",
    "improvement": "Ziara iliharakishwa na ilianza kuchelewa.",
    "original_favorite": "The museum collection was interesting.",
    "original_improvement": "The tour felt rushed and started late.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-01-07",
    "favorite": "Ziara ya majengo ilikuwa na maelezo mengi na ilipangwa vizuri.",
    "improvement": "Ramani ya njia ingekuwa na manufaa.",
    "original_favorite": "The architecture tour was informative and well organized.",
    "original_improvement": "A map of the route would be useful.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-01-09",
    "favorite": "Jengo la kihistoria lilivutia sana.",
    "improvement": "Mwongoza watalii anapaswa kuzungumza polepole na kutumia kipaza sauti.",
    "original_favorite": "The historic building was impressive.",
    "original_improvement": "The guide should speak more slowly and use a microphone.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-01-11",
    "favorite": "Usimulizi wa hadithi ulifanya masimulizi ya kale yaonekane halisi.",
    "improvement": "Kijitabu kifupi cha hadithi kingekuwa kumbukumbu nzuri.",
    "original_favorite": "The storytelling made the legends feel alive.",
    "original_improvement": "A short booklet with the stories would be a great souvenir.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-01-13",
    "favorite": "Kipindi cha kupiga picha wakati wa machweo kilikuwa cha kukumbukwa.",
    "improvement": "Tafadhali tutumieni taarifa za hali ya hewa kabla ya kipindi hicho.",
    "original_favorite": "The sunset photography session was memorable.",
    "original_improvement": "Please send weather updates before the session.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-01-15",
    "favorite": "Ziara ilikuwa rahisi kufikiwa na wafanyakazi walijali mahitaji yetu.",
    "improvement": "Tafadhali chapisheni maelezo ya ufikivu mapema.",
    "original_favorite": "The tour was accessible and the staff were considerate.",
    "original_improvement": "Please publish accessibility details in advance.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-01-17",
    "favorite": "Ziara ilitupa uzoefu halisi wa maisha ya wenyeji.",
    "improvement": "Ningependa chaguo la kundi dogo zaidi.",
    "original_favorite": "The experience felt authentic rather than touristy.",
    "original_improvement": "I would love an option for an even smaller group.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-02-01",
    "favorite": "Mwongoza watalii alijibu kila swali kwa uvumilivu.",
    "improvement": "Hakuna jambo kubwa linalohitaji kuboreshwa.",
    "original_favorite": "The guide answered every question with patience.",
    "original_improvement": "Nothing major needs improvement.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-02-03",
    "favorite": "Sehemu za kusimama kupiga picha zilichaguliwa vizuri sana.",
    "improvement": "Ziara ingeweza kutoa huduma ya mpiga picha mtaalamu.",
    "original_favorite": "The photography stops were perfectly chosen.",
    "original_improvement": "The tour could offer a professional photography option.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-02-05",
    "favorite": "Bustani ya mimea ilikuwa na aina nyingi za mimea ya kuvutia.",
    "improvement": "Majina ya mimea yangeweza kuonyeshwa kwa uwazi zaidi.",
    "original_favorite": "The botanical garden had an amazing variety of plants.",
    "original_improvement": "The plant names could be displayed more clearly.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-02-07",
    "favorite": "Wanajamii walikuwa wakarimu na wenye ukarimu kwa wageni.",
    "improvement": "Ningefurahia mazungumzo marefu zaidi na wenyeji.",
    "original_favorite": "The community members were generous and welcoming.",
    "original_improvement": "I would enjoy a longer conversation with the hosts.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-02-09",
    "favorite": "Safari ya mashua ilitupa mandhari tofauti ya jiji.",
    "improvement": "Injini ya mashua ilikuwa na kelele wakati maelezo yalipotolewa.",
    "original_favorite": "The boat ride offered a different view of the city.",
    "original_improvement": "The boat engine was noisy during the explanations.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-02-11",
    "favorite": "Mwongoza watalii alitupa maelezo ya kina kuhusu mfumo wa ikolojia wa eneo hilo.",
    "improvement": "Njia ingeweza kuwa na alama zilizo wazi zaidi.",
    "original_favorite": "The guide gave us a detailed explanation of the local ecosystem.",
    "original_improvement": "The route could have clearer signs.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-02-13",
    "favorite": "Njia ya matembezi ilituonyesha maeneo ambayo tusingeyapata wenyewe.",
    "improvement": "Tafadhali tupatie maelezo ya njia kabla ya ziara.",
    "original_favorite": "The walking route showed us places we would not have found alone.",
    "original_improvement": "Please provide the route details before the tour.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-02-15",
    "favorite": "Matembezi ya kutazama wanyamapori yalituwezesha kuona wanyama wengi.",
    "improvement": "Kila mgeni anapaswa kupewa darubini.",
    "original_favorite": "The wildlife walk gave us several great sightings.",
    "original_improvement": "Binoculars should be available for every guest.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-03-03",
    "favorite": "Ufukwe ulikuwa mtulivu na mwongoza watalii alikuwa bora sana.",
    "improvement": "Tafadhali toeni chupa za maji zinazoweza kutumika tena.",
    "original_favorite": "The beach was peaceful and the guide was excellent.",
    "original_improvement": "Please provide reusable water bottles.",
    "is_demo": true
  },
  {
    "rating": 1,
    "language": "sw",
    "date": "2026-03-07",
    "favorite": "Mandhari katika kituo cha mwisho cha kutazamia yalikuwa mazuri.",
    "improvement": "Ziara ilifutwa dakika za mwisho na ile mbadala ilipangwa vibaya.",
    "original_favorite": "The final viewpoint was beautiful.",
    "original_improvement": "The tour was canceled late and the replacement was poorly organized.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-03-11",
    "favorite": "Onyesho la ngoma za jadi lilikuwa lenye nguvu na la kusisimua.",
    "improvement": "Mwonekano kutoka sehemu ya nyuma ya ukumbi ungeweza kuboreshwa.",
    "original_favorite": "The traditional dance performance was vibrant and exciting.",
    "original_improvement": "The venue could have better visibility from the back.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-03-15",
    "favorite": "Eneo tulilofika lilistahili kutembelewa.",
    "improvement": "Ratiba ilibadilishwa bila taarifa ya kutosha.",
    "original_favorite": "The destination itself was worth visiting.",
    "original_improvement": "The schedule changed without enough notice.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-03-19",
    "favorite": "Mwongoza watalii alisimulia hadithi za kuvutia kuhusu jamii.",
    "improvement": "Ziara inapaswa kuanza mapema kidogo.",
    "original_favorite": "The guide shared fascinating stories about the community.",
    "original_improvement": "The tour should start a little earlier.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-03-23",
    "favorite": "Maelezo kuhusu utamaduni yalitolewa kwa makini.",
    "improvement": "Kunapaswa kuwa na sehemu zaidi za kukaa njiani.",
    "original_favorite": "The cultural explanations were thoughtful.",
    "original_improvement": "There should be more seating along the route.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-03-27",
    "favorite": "Mwongoza watalii alitukaribisha vizuri na alitufanya tujisikie salama.",
    "improvement": "Maelezo mafupi kuhusu usalama mwanzoni yangesaidia.",
    "original_favorite": "The guide was welcoming and made us feel safe.",
    "original_improvement": "Adding a brief introduction about safety would help.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-04-01",
    "favorite": "Mwongoza watalii alikumbuka jina la kila mtu na aliunganisha kundi vizuri.",
    "improvement": "Utaratibu wa kujiandikisha ungeweza kuwa wa haraka zaidi.",
    "original_favorite": "The guide remembered everyone's name and made the group feel connected.",
    "original_improvement": "The check-in process could be faster.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-04-03",
    "favorite": "Mazingira ya jioni na muziki wa moja kwa moja vilikuwa vizuri sana.",
    "improvement": "Hafla ingeweza kuwa na meza zaidi.",
    "original_favorite": "The evening atmosphere and live music were wonderful.",
    "original_improvement": "The event could include a few more tables.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-04-05",
    "favorite": "Vyakula vya wenyeji tulivyoonja vilikuwa vitamu.",
    "improvement": "Sehemu ya kukutana ilikuwa ngumu kuipata.",
    "original_favorite": "The local food tasting was delicious.",
    "original_improvement": "The meeting point was difficult to find.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-04-07",
    "favorite": "Onyesho la upishi lilitushirikisha na lilivutia.",
    "improvement": "Ningependa kupewa maelekezo ya mapishi yaliyochapishwa.",
    "original_favorite": "The cooking demonstration was personal and engaging.",
    "original_improvement": "I would have liked a printed recipe.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-04-09",
    "favorite": "Onyesho la muziki lilikuwa jambo bora zaidi jioni yetu.",
    "improvement": "Mpangilio wa viti ungeweza kuwa wa kustarehesha zaidi.",
    "original_favorite": "The music performance was the highlight of our evening.",
    "original_improvement": "The seating arrangement could be more comfortable.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-04-11",
    "favorite": "Warsha ya ufundi ilikuwa ya ubunifu na ya kufurahisha.",
    "improvement": "Vifaa viliisha kabla ya kila mtu kumaliza.",
    "original_favorite": "The craft workshop was creative and enjoyable.",
    "original_improvement": "The materials ran out before everyone finished.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-04-13",
    "favorite": "Mwongoza watalii alitupa mapendekezo mazuri kwa sehemu iliyobaki ya safari yetu.",
    "improvement": "Orodha ya mapendekezo baada ya ziara ingekuwa na manufaa.",
    "original_favorite": "The guide gave excellent recommendations for the rest of our trip.",
    "original_improvement": "A list of recommendations would be useful afterward.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-05-01",
    "favorite": "Mandhari kutoka sehemu ya kutazamia yalikuwa ya kuvutia sana.",
    "improvement": "Muda zaidi wa kupiga picha ungekuwa mzuri.",
    "original_favorite": "The views from the lookout were incredible.",
    "original_improvement": "More time for photos would be helpful.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-05-03",
    "favorite": "Mandhari ya jua likitua juu ya mto yalikuwa mazuri.",
    "improvement": "Maelekezo kuhusu sehemu ya kuchukuliwa na usafiri yawe wazi zaidi.",
    "original_favorite": "The sunset over the river was beautiful.",
    "original_improvement": "The transport pickup instructions could be clearer.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-05-05",
    "favorite": "Nilifurahia kutembelea bustani ya jamii.",
    "improvement": "Ziara ilihitaji mpangilio bora kati ya vituo.",
    "original_favorite": "I enjoyed the visit to the community garden.",
    "original_improvement": "The tour needed better organization between stops.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-05-07",
    "favorite": "Safari ya mashua mtoni ilikuwa ya kustarehesha na yenye mandhari mazuri.",
    "improvement": "Sehemu zaidi za kivuli kwenye mashua zingesaidia.",
    "original_favorite": "The river cruise was relaxing and scenic.",
    "original_improvement": "A few more shade areas on the boat would be helpful.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-05-09",
    "favorite": "Njia ya baiskeli ilikuwa na mandhari mazuri na ilifurahisha.",
    "improvement": "Baiskeli zinahitaji viti vya kustarehesha zaidi.",
    "original_favorite": "The cycling route was scenic and enjoyable.",
    "original_improvement": "The bicycles need more comfortable seats.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-05-11",
    "favorite": "Ziara ilitupa uhusiano wa maana na utamaduni wa wenyeji.",
    "improvement": "Tafadhali pangeni ziara hii katika siku zaidi.",
    "original_favorite": "The tour gave us a meaningful connection to the local culture.",
    "original_improvement": "Please offer this experience on more days.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-05-13",
    "favorite": "Kila kituo kilivutia na kasi ya ziara ilikuwa nzuri sana.",
    "improvement": "Ziara ilikuwa nzuri sana ilivyokuwa.",
    "original_favorite": "Every stop was interesting and the pacing was excellent.",
    "original_improvement": "The tour was excellent as it was.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-05-15",
    "favorite": "Nilifurahia kujifunza historia ya mji wa kale.",
    "improvement": "Kundi lilikuwa kubwa kidogo.",
    "original_favorite": "I loved learning about the history of the old town.",
    "original_improvement": "The group was a little too large.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-06-03",
    "favorite": "Matembezi ya kuelekea maporomoko ya maji yalikuwa magumu lakini yalifurahisha.",
    "improvement": "Tafadhali elezeni kwa uwazi zaidi kiwango cha ugumu wa matembezi.",
    "original_favorite": "The waterfall hike was challenging but rewarding.",
    "original_improvement": "Please describe the hike difficulty more clearly.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-06-07",
    "favorite": "Nilipenda jinsi kundi letu lilivyokuwa dogo.",
    "improvement": "Barua pepe ya uthibitisho inapaswa kujumuisha maelezo ya maegesho.",
    "original_favorite": "I appreciated the small group size.",
    "original_improvement": "The confirmation email should include parking information.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-06-11",
    "favorite": "Vitafunio vya wenyeji vilikuwa sehemu niliyoipenda zaidi.",
    "improvement": "Ziara inapaswa kutoa muda zaidi katika vituo vya chakula.",
    "original_favorite": "The local snacks were my favorite part.",
    "original_improvement": "The tour should have more time at the food stops.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-06-15",
    "favorite": "Mwongoza watalii alikuwa mcheshi sana.",
    "improvement": "Ratiba ya safari inapaswa kuelezwa mwanzoni.",
    "original_favorite": "The guide had a great sense of humor.",
    "original_improvement": "The itinerary should be shared at the beginning.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-06-19",
    "favorite": "Zawadi iliyotengenezwa kwa mikono ilikuwa kumbukumbu nzuri ya ziara.",
    "improvement": "Miundo zaidi ya zawadi za kumbukumbu ingependeza.",
    "original_favorite": "The handmade souvenir was a lovely reminder of the visit.",
    "original_improvement": "More souvenir designs would be interesting.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-06-23",
    "favorite": "Mwongoza watalii alikuwa mwenye urafiki na maarifa mengi.",
    "improvement": "Ziara ingeweza kujumuisha mapumziko mafupi.",
    "original_favorite": "The guide was friendly and very knowledgeable.",
    "original_improvement": "The tour could include a short rest break.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-06-27",
    "favorite": "Vitu vilivyoonyeshwa katika jumba la makumbusho vilivutia.",
    "improvement": "Ziara iliharakishwa na ilianza kuchelewa.",
    "original_favorite": "The museum collection was interesting.",
    "original_improvement": "The tour felt rushed and started late.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-07-01",
    "favorite": "Usimulizi wa hadithi ulifanya masimulizi ya kale yaonekane halisi.",
    "improvement": "Kijitabu kifupi cha hadithi kingekuwa kumbukumbu nzuri.",
    "original_favorite": "The storytelling made the legends feel alive.",
    "original_improvement": "A short booklet with the stories would be a great souvenir.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-07-05",
    "favorite": "Kipindi cha kupiga picha wakati wa machweo kilikuwa cha kukumbukwa.",
    "improvement": "Tafadhali tutumieni taarifa za hali ya hewa kabla ya kipindi hicho.",
    "original_favorite": "The sunset photography session was memorable.",
    "original_improvement": "Please send weather updates before the session.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-07-09",
    "favorite": "Ziara ilikuwa rahisi kufikiwa na wafanyakazi walijali mahitaji yetu.",
    "improvement": "Tafadhali chapisheni maelezo ya ufikivu mapema.",
    "original_favorite": "The tour was accessible and the staff were considerate.",
    "original_improvement": "Please publish accessibility details in advance.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-07-13",
    "favorite": "Ziara ilitupa uzoefu halisi wa maisha ya wenyeji.",
    "improvement": "Ningependa chaguo la kundi dogo zaidi.",
    "original_favorite": "The experience felt authentic rather than touristy.",
    "original_improvement": "I would love an option for an even smaller group.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-07-17",
    "favorite": "Nilifurahia kukutana na wasanii wa eneo hilo sokoni.",
    "improvement": "Sauti ya mfumo wa sauti ingeweza kuongezwa.",
    "original_favorite": "I enjoyed meeting local artists at the market.",
    "original_improvement": "The audio system could be louder.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-07-21",
    "favorite": "Mwongoza watalii alijibu kila swali kwa uvumilivu.",
    "improvement": "Hakuna jambo kubwa linalohitaji kuboreshwa.",
    "original_favorite": "The guide answered every question with patience.",
    "original_improvement": "Nothing major needs improvement.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-07-23",
    "favorite": "Sehemu za kusimama kupiga picha zilichaguliwa vizuri sana.",
    "improvement": "Ziara ingeweza kutoa huduma ya mpiga picha mtaalamu.",
    "original_favorite": "The photography stops were perfectly chosen.",
    "original_improvement": "The tour could offer a professional photography option.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-07-25",
    "favorite": "Bustani ya mimea ilikuwa na aina nyingi za mimea ya kuvutia.",
    "improvement": "Majina ya mimea yangeweza kuonyeshwa kwa uwazi zaidi.",
    "original_favorite": "The botanical garden had an amazing variety of plants.",
    "original_improvement": "The plant names could be displayed more clearly.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-07-27",
    "favorite": "Wanajamii walikuwa wakarimu na wenye ukarimu kwa wageni.",
    "improvement": "Ningefurahia mazungumzo marefu zaidi na wenyeji.",
    "original_favorite": "The community members were generous and welcoming.",
    "original_improvement": "I would enjoy a longer conversation with the hosts.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-07-02",
    "favorite": "Safari ya mashua ilitupa mandhari tofauti ya jiji.",
    "improvement": "Injini ya mashua ilikuwa na kelele wakati maelezo yalipotolewa.",
    "original_favorite": "The boat ride offered a different view of the city.",
    "original_improvement": "The boat engine was noisy during the explanations.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-08-01",
    "favorite": "Safari ya mashua ilitupa mandhari tofauti ya jiji.",
    "improvement": "Injini ya mashua ilikuwa na kelele wakati maelezo yalipotolewa.",
    "original_favorite": "The boat ride offered a different view of the city.",
    "original_improvement": "The boat engine was noisy during the explanations.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-08-03",
    "favorite": "Mwongoza watalii alitupa maelezo ya kina kuhusu mfumo wa ikolojia wa eneo hilo.",
    "improvement": "Njia ingeweza kuwa na alama zilizo wazi zaidi.",
    "original_favorite": "The guide gave us a detailed explanation of the local ecosystem.",
    "original_improvement": "The route could have clearer signs.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-08-05",
    "favorite": "Njia ya matembezi ilituonyesha maeneo ambayo tusingeyapata wenyewe.",
    "improvement": "Tafadhali tupatie maelezo ya njia kabla ya ziara.",
    "original_favorite": "The walking route showed us places we would not have found alone.",
    "original_improvement": "Please provide the route details before the tour.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-08-07",
    "favorite": "Matembezi ya kutazama wanyamapori yalituwezesha kuona wanyama wengi.",
    "improvement": "Kila mgeni anapaswa kupewa darubini.",
    "original_favorite": "The wildlife walk gave us several great sightings.",
    "original_improvement": "Binoculars should be available for every guest.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-08-09",
    "favorite": "Ziara ya soko ilitupa nafasi nzuri ya kujionea maisha ya wenyeji.",
    "improvement": "Chaguo zaidi za vyakula visivyo na nyama zingekuwa nzuri.",
    "original_favorite": "The market tour gave us a great taste of local life.",
    "original_improvement": "More vegetarian tasting options would be nice.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-08-11",
    "favorite": "Ufukwe ulikuwa mtulivu na mwongoza watalii alikuwa bora sana.",
    "improvement": "Tafadhali toeni chupa za maji zinazoweza kutumika tena.",
    "original_favorite": "The beach was peaceful and the guide was excellent.",
    "original_improvement": "Please provide reusable water bottles.",
    "is_demo": true
  },
  {
    "rating": 1,
    "language": "sw",
    "date": "2026-08-13",
    "favorite": "Mandhari katika kituo cha mwisho cha kutazamia yalikuwa mazuri.",
    "improvement": "Ziara ilifutwa dakika za mwisho na ile mbadala ilipangwa vibaya.",
    "original_favorite": "The final viewpoint was beautiful.",
    "original_improvement": "The tour was canceled late and the replacement was poorly organized.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-08-15",
    "favorite": "Onyesho la ngoma za jadi lilikuwa lenye nguvu na la kusisimua.",
    "improvement": "Mwonekano kutoka sehemu ya nyuma ya ukumbi ungeweza kuboreshwa.",
    "original_favorite": "The traditional dance performance was vibrant and exciting.",
    "original_improvement": "The venue could have better visibility from the back.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-08-17",
    "favorite": "Eneo tulilofika lilistahili kutembelewa.",
    "improvement": "Ratiba ilibadilishwa bila taarifa ya kutosha.",
    "original_favorite": "The destination itself was worth visiting.",
    "original_improvement": "The schedule changed without enough notice.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-08-19",
    "favorite": "Mwongoza watalii alisimulia hadithi za kuvutia kuhusu jamii.",
    "improvement": "Ziara inapaswa kuanza mapema kidogo.",
    "original_favorite": "The guide shared fascinating stories about the community.",
    "original_improvement": "The tour should start a little earlier.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-08-21",
    "favorite": "Maelezo kuhusu utamaduni yalitolewa kwa makini.",
    "improvement": "Kunapaswa kuwa na sehemu zaidi za kukaa njiani.",
    "original_favorite": "The cultural explanations were thoughtful.",
    "original_improvement": "There should be more seating along the route.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-08-23",
    "favorite": "Mwongoza watalii alitukaribisha vizuri na alitufanya tujisikie salama.",
    "improvement": "Maelezo mafupi kuhusu usalama mwanzoni yangesaidia.",
    "original_favorite": "The guide was welcoming and made us feel safe.",
    "original_improvement": "Adding a brief introduction about safety would help.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-08-25",
    "favorite": "Historia ya eneo hilo ilisimuliwa kwa njia ya kuvutia.",
    "improvement": "Ziara inapaswa kujumuisha picha zaidi za kihistoria.",
    "original_favorite": "The neighborhood history was presented in an engaging way.",
    "original_improvement": "The tour should include more historical photographs.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-08-27",
    "favorite": "Maeneo madogo ya kihistoria yalikuwa hazina zilizofichika.",
    "improvement": "Njia inapaswa kujumuisha mapumziko zaidi ya kutumia vyoo.",
    "original_favorite": "The small historical sites were hidden gems.",
    "original_improvement": "The route should include more restroom breaks.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-08-02",
    "favorite": "Mwongoza watalii alikumbuka jina la kila mtu na aliunganisha kundi vizuri.",
    "improvement": "Utaratibu wa kujiandikisha ungeweza kuwa wa haraka zaidi.",
    "original_favorite": "The guide remembered everyone's name and made the group feel connected.",
    "original_improvement": "The check-in process could be faster.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-09-01",
    "favorite": "Mwongoza watalii alisimulia hadithi za kuvutia kuhusu jamii.",
    "improvement": "Ziara inapaswa kuanza mapema kidogo.",
    "original_favorite": "The guide shared fascinating stories about the community.",
    "original_improvement": "The tour should start a little earlier.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-09-03",
    "favorite": "Maelezo kuhusu utamaduni yalitolewa kwa makini.",
    "improvement": "Kunapaswa kuwa na sehemu zaidi za kukaa njiani.",
    "original_favorite": "The cultural explanations were thoughtful.",
    "original_improvement": "There should be more seating along the route.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-09-05",
    "favorite": "Mwongoza watalii alitukaribisha vizuri na alitufanya tujisikie salama.",
    "improvement": "Maelezo mafupi kuhusu usalama mwanzoni yangesaidia.",
    "original_favorite": "The guide was welcoming and made us feel safe.",
    "original_improvement": "Adding a brief introduction about safety would help.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-09-07",
    "favorite": "Historia ya eneo hilo ilisimuliwa kwa njia ya kuvutia.",
    "improvement": "Ziara inapaswa kujumuisha picha zaidi za kihistoria.",
    "original_favorite": "The neighborhood history was presented in an engaging way.",
    "original_improvement": "The tour should include more historical photographs.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-09-09",
    "favorite": "Maeneo madogo ya kihistoria yalikuwa hazina zilizofichika.",
    "improvement": "Njia inapaswa kujumuisha mapumziko zaidi ya kutumia vyoo.",
    "original_favorite": "The small historical sites were hidden gems.",
    "original_improvement": "The route should include more restroom breaks.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-09-11",
    "favorite": "Mwongoza watalii alikumbuka jina la kila mtu na aliunganisha kundi vizuri.",
    "improvement": "Utaratibu wa kujiandikisha ungeweza kuwa wa haraka zaidi.",
    "original_favorite": "The guide remembered everyone's name and made the group feel connected.",
    "original_improvement": "The check-in process could be faster.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-09-13",
    "favorite": "Mazingira ya jioni na muziki wa moja kwa moja vilikuwa vizuri sana.",
    "improvement": "Hafla ingeweza kuwa na meza zaidi.",
    "original_favorite": "The evening atmosphere and live music were wonderful.",
    "original_improvement": "The event could include a few more tables.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-09-15",
    "favorite": "Vyakula vya wenyeji tulivyoonja vilikuwa vitamu.",
    "improvement": "Sehemu ya kukutana ilikuwa ngumu kuipata.",
    "original_favorite": "The local food tasting was delicious.",
    "original_improvement": "The meeting point was difficult to find.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-09-17",
    "favorite": "Onyesho la upishi lilitushirikisha na lilivutia.",
    "improvement": "Ningependa kupewa maelekezo ya mapishi yaliyochapishwa.",
    "original_favorite": "The cooking demonstration was personal and engaging.",
    "original_improvement": "I would have liked a printed recipe.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-09-19",
    "favorite": "Onyesho la muziki lilikuwa jambo bora zaidi jioni yetu.",
    "improvement": "Mpangilio wa viti ungeweza kuwa wa kustarehesha zaidi.",
    "original_favorite": "The music performance was the highlight of our evening.",
    "original_improvement": "The seating arrangement could be more comfortable.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-09-21",
    "favorite": "Warsha ya ufundi ilikuwa ya ubunifu na ya kufurahisha.",
    "improvement": "Vifaa viliisha kabla ya kila mtu kumaliza.",
    "original_favorite": "The craft workshop was creative and enjoyable.",
    "original_improvement": "The materials ran out before everyone finished.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-09-23",
    "favorite": "Mwongoza watalii alitupa mapendekezo mazuri kwa sehemu iliyobaki ya safari yetu.",
    "improvement": "Orodha ya mapendekezo baada ya ziara ingekuwa na manufaa.",
    "original_favorite": "The guide gave excellent recommendations for the rest of our trip.",
    "original_improvement": "A list of recommendations would be useful afterward.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-09-25",
    "favorite": "Matembezi msituni yalikuwa ya utulivu na yenye mandhari mazuri.",
    "improvement": "Maelezo zaidi kuhusu mimea ya eneo hilo yangependeza.",
    "original_favorite": "The forest walk was calm and beautiful.",
    "original_improvement": "More information about the local plants would be welcome.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-09-27",
    "favorite": "Mwongoza watalii alieleza mila kwa heshima.",
    "improvement": "Kipeperushi chenye tafsiri kingewasaidia wageni wa kimataifa.",
    "original_favorite": "The guide explained the traditions respectfully.",
    "original_improvement": "A translation handout would help international visitors.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-09-02",
    "favorite": "Mandhari kutoka sehemu ya kutazamia yalikuwa ya kuvutia sana.",
    "improvement": "Muda zaidi wa kupiga picha ungekuwa mzuri.",
    "original_favorite": "The views from the lookout were incredible.",
    "original_improvement": "More time for photos would be helpful.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-10-01",
    "favorite": "Onyesho la muziki lilikuwa jambo bora zaidi jioni yetu.",
    "improvement": "Mpangilio wa viti ungeweza kuwa wa kustarehesha zaidi.",
    "original_favorite": "The music performance was the highlight of our evening.",
    "original_improvement": "The seating arrangement could be more comfortable.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-10-03",
    "favorite": "Warsha ya ufundi ilikuwa ya ubunifu na ya kufurahisha.",
    "improvement": "Vifaa viliisha kabla ya kila mtu kumaliza.",
    "original_favorite": "The craft workshop was creative and enjoyable.",
    "original_improvement": "The materials ran out before everyone finished.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-10-05",
    "favorite": "Mwongoza watalii alitupa mapendekezo mazuri kwa sehemu iliyobaki ya safari yetu.",
    "improvement": "Orodha ya mapendekezo baada ya ziara ingekuwa na manufaa.",
    "original_favorite": "The guide gave excellent recommendations for the rest of our trip.",
    "original_improvement": "A list of recommendations would be useful afterward.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-10-07",
    "favorite": "Matembezi msituni yalikuwa ya utulivu na yenye mandhari mazuri.",
    "improvement": "Maelezo zaidi kuhusu mimea ya eneo hilo yangependeza.",
    "original_favorite": "The forest walk was calm and beautiful.",
    "original_improvement": "More information about the local plants would be welcome.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-10-09",
    "favorite": "Mwongoza watalii alieleza mila kwa heshima.",
    "improvement": "Kipeperushi chenye tafsiri kingewasaidia wageni wa kimataifa.",
    "original_favorite": "The guide explained the traditions respectfully.",
    "original_improvement": "A translation handout would help international visitors.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-10-11",
    "favorite": "Mandhari kutoka sehemu ya kutazamia yalikuwa ya kuvutia sana.",
    "improvement": "Muda zaidi wa kupiga picha ungekuwa mzuri.",
    "original_favorite": "The views from the lookout were incredible.",
    "original_improvement": "More time for photos would be helpful.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-10-13",
    "favorite": "Mandhari ya jua likitua juu ya mto yalikuwa mazuri.",
    "improvement": "Maelekezo kuhusu sehemu ya kuchukuliwa na usafiri yawe wazi zaidi.",
    "original_favorite": "The sunset over the river was beautiful.",
    "original_improvement": "The transport pickup instructions could be clearer.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-10-15",
    "favorite": "Nilifurahia kutembelea bustani ya jamii.",
    "improvement": "Ziara ilihitaji mpangilio bora kati ya vituo.",
    "original_favorite": "I enjoyed the visit to the community garden.",
    "original_improvement": "The tour needed better organization between stops.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-10-17",
    "favorite": "Safari ya mashua mtoni ilikuwa ya kustarehesha na yenye mandhari mazuri.",
    "improvement": "Sehemu zaidi za kivuli kwenye mashua zingesaidia.",
    "original_favorite": "The river cruise was relaxing and scenic.",
    "original_improvement": "A few more shade areas on the boat would be helpful.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-10-19",
    "favorite": "Njia ya baiskeli ilikuwa na mandhari mazuri na ilifurahisha.",
    "improvement": "Baiskeli zinahitaji viti vya kustarehesha zaidi.",
    "original_favorite": "The cycling route was scenic and enjoyable.",
    "original_improvement": "The bicycles need more comfortable seats.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-10-21",
    "favorite": "Ziara ilitupa uhusiano wa maana na utamaduni wa wenyeji.",
    "improvement": "Tafadhali pangeni ziara hii katika siku zaidi.",
    "original_favorite": "The tour gave us a meaningful connection to the local culture.",
    "original_improvement": "Please offer this experience on more days.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-10-23",
    "favorite": "Kila kituo kilivutia na kasi ya ziara ilikuwa nzuri sana.",
    "improvement": "Ziara ilikuwa nzuri sana ilivyokuwa.",
    "original_favorite": "Every stop was interesting and the pacing was excellent.",
    "original_improvement": "The tour was excellent as it was.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-10-25",
    "favorite": "Nilifurahia kujifunza historia ya mji wa kale.",
    "improvement": "Kundi lilikuwa kubwa kidogo.",
    "original_favorite": "I loved learning about the history of the old town.",
    "original_improvement": "The group was a little too large.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-10-27",
    "favorite": "Mwongoza watalii wetu aliifanya ziara nzima iwafurahishe watoto.",
    "improvement": "Punguzo kwa familia lingependeza.",
    "original_favorite": "Our guide made the entire experience fun for the children.",
    "original_improvement": "A family discount would be appreciated.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-10-02",
    "favorite": "Matembezi ya kuelekea maporomoko ya maji yalikuwa magumu lakini yalifurahisha.",
    "improvement": "Tafadhali elezeni kwa uwazi zaidi kiwango cha ugumu wa matembezi.",
    "original_favorite": "The waterfall hike was challenging but rewarding.",
    "original_improvement": "Please describe the hike difficulty more clearly.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-11-01",
    "favorite": "Njia ya baiskeli ilikuwa na mandhari mazuri na ilifurahisha.",
    "improvement": "Baiskeli zinahitaji viti vya kustarehesha zaidi.",
    "original_favorite": "The cycling route was scenic and enjoyable.",
    "original_improvement": "The bicycles need more comfortable seats.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-11-03",
    "favorite": "Ziara ilitupa uhusiano wa maana na utamaduni wa wenyeji.",
    "improvement": "Tafadhali pangeni ziara hii katika siku zaidi.",
    "original_favorite": "The tour gave us a meaningful connection to the local culture.",
    "original_improvement": "Please offer this experience on more days.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-11-05",
    "favorite": "Kila kituo kilivutia na kasi ya ziara ilikuwa nzuri sana.",
    "improvement": "Ziara ilikuwa nzuri sana ilivyokuwa.",
    "original_favorite": "Every stop was interesting and the pacing was excellent.",
    "original_improvement": "The tour was excellent as it was.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-11-07",
    "favorite": "Nilifurahia kujifunza historia ya mji wa kale.",
    "improvement": "Kundi lilikuwa kubwa kidogo.",
    "original_favorite": "I loved learning about the history of the old town.",
    "original_improvement": "The group was a little too large.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-11-09",
    "favorite": "Mwongoza watalii wetu aliifanya ziara nzima iwafurahishe watoto.",
    "improvement": "Punguzo kwa familia lingependeza.",
    "original_favorite": "Our guide made the entire experience fun for the children.",
    "original_improvement": "A family discount would be appreciated.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-11-11",
    "favorite": "Matembezi ya kuelekea maporomoko ya maji yalikuwa magumu lakini yalifurahisha.",
    "improvement": "Tafadhali elezeni kwa uwazi zaidi kiwango cha ugumu wa matembezi.",
    "original_favorite": "The waterfall hike was challenging but rewarding.",
    "original_improvement": "Please describe the hike difficulty more clearly.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-11-13",
    "favorite": "Nilipenda jinsi kundi letu lilivyokuwa dogo.",
    "improvement": "Barua pepe ya uthibitisho inapaswa kujumuisha maelezo ya maegesho.",
    "original_favorite": "I appreciated the small group size.",
    "original_improvement": "The confirmation email should include parking information.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-11-15",
    "favorite": "Vitafunio vya wenyeji vilikuwa sehemu niliyoipenda zaidi.",
    "improvement": "Ziara inapaswa kutoa muda zaidi katika vituo vya chakula.",
    "original_favorite": "The local snacks were my favorite part.",
    "original_improvement": "The tour should have more time at the food stops.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-11-17",
    "favorite": "Mwongoza watalii alikuwa mcheshi sana.",
    "improvement": "Ratiba ya safari inapaswa kuelezwa mwanzoni.",
    "original_favorite": "The guide had a great sense of humor.",
    "original_improvement": "The itinerary should be shared at the beginning.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-11-19",
    "favorite": "Zawadi iliyotengenezwa kwa mikono ilikuwa kumbukumbu nzuri ya ziara.",
    "improvement": "Miundo zaidi ya zawadi za kumbukumbu ingependeza.",
    "original_favorite": "The handmade souvenir was a lovely reminder of the visit.",
    "original_improvement": "More souvenir designs would be interesting.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-11-21",
    "favorite": "Mwongoza watalii alikuwa mwenye urafiki na maarifa mengi.",
    "improvement": "Ziara ingeweza kujumuisha mapumziko mafupi.",
    "original_favorite": "The guide was friendly and very knowledgeable.",
    "original_improvement": "The tour could include a short rest break.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-11-23",
    "favorite": "Vitu vilivyoonyeshwa katika jumba la makumbusho vilivutia.",
    "improvement": "Ziara iliharakishwa na ilianza kuchelewa.",
    "original_favorite": "The museum collection was interesting.",
    "original_improvement": "The tour felt rushed and started late.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-11-25",
    "favorite": "Ziara ya majengo ilikuwa na maelezo mengi na ilipangwa vizuri.",
    "improvement": "Ramani ya njia ingekuwa na manufaa.",
    "original_favorite": "The architecture tour was informative and well organized.",
    "original_improvement": "A map of the route would be useful.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-11-27",
    "favorite": "Jengo la kihistoria lilivutia sana.",
    "improvement": "Mwongoza watalii anapaswa kuzungumza polepole na kutumia kipaza sauti.",
    "original_favorite": "The historic building was impressive.",
    "original_improvement": "The guide should speak more slowly and use a microphone.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-11-02",
    "favorite": "Usimulizi wa hadithi ulifanya masimulizi ya kale yaonekane halisi.",
    "improvement": "Kijitabu kifupi cha hadithi kingekuwa kumbukumbu nzuri.",
    "original_favorite": "The storytelling made the legends feel alive.",
    "original_improvement": "A short booklet with the stories would be a great souvenir.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-12-01",
    "favorite": "Zawadi iliyotengenezwa kwa mikono ilikuwa kumbukumbu nzuri ya ziara.",
    "improvement": "Miundo zaidi ya zawadi za kumbukumbu ingependeza.",
    "original_favorite": "The handmade souvenir was a lovely reminder of the visit.",
    "original_improvement": "More souvenir designs would be interesting.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-12-03",
    "favorite": "Mwongoza watalii alikuwa mwenye urafiki na maarifa mengi.",
    "improvement": "Ziara ingeweza kujumuisha mapumziko mafupi.",
    "original_favorite": "The guide was friendly and very knowledgeable.",
    "original_improvement": "The tour could include a short rest break.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-12-05",
    "favorite": "Vitu vilivyoonyeshwa katika jumba la makumbusho vilivutia.",
    "improvement": "Ziara iliharakishwa na ilianza kuchelewa.",
    "original_favorite": "The museum collection was interesting.",
    "original_improvement": "The tour felt rushed and started late.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-12-07",
    "favorite": "Ziara ya majengo ilikuwa na maelezo mengi na ilipangwa vizuri.",
    "improvement": "Ramani ya njia ingekuwa na manufaa.",
    "original_favorite": "The architecture tour was informative and well organized.",
    "original_improvement": "A map of the route would be useful.",
    "is_demo": true
  },
  {
    "rating": 2,
    "language": "sw",
    "date": "2026-12-09",
    "favorite": "Jengo la kihistoria lilivutia sana.",
    "improvement": "Mwongoza watalii anapaswa kuzungumza polepole na kutumia kipaza sauti.",
    "original_favorite": "The historic building was impressive.",
    "original_improvement": "The guide should speak more slowly and use a microphone.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-12-11",
    "favorite": "Usimulizi wa hadithi ulifanya masimulizi ya kale yaonekane halisi.",
    "improvement": "Kijitabu kifupi cha hadithi kingekuwa kumbukumbu nzuri.",
    "original_favorite": "The storytelling made the legends feel alive.",
    "original_improvement": "A short booklet with the stories would be a great souvenir.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-12-13",
    "favorite": "Kipindi cha kupiga picha wakati wa machweo kilikuwa cha kukumbukwa.",
    "improvement": "Tafadhali tutumieni taarifa za hali ya hewa kabla ya kipindi hicho.",
    "original_favorite": "The sunset photography session was memorable.",
    "original_improvement": "Please send weather updates before the session.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-12-15",
    "favorite": "Ziara ilikuwa rahisi kufikiwa na wafanyakazi walijali mahitaji yetu.",
    "improvement": "Tafadhali chapisheni maelezo ya ufikivu mapema.",
    "original_favorite": "The tour was accessible and the staff were considerate.",
    "original_improvement": "Please publish accessibility details in advance.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-12-17",
    "favorite": "Ziara ilitupa uzoefu halisi wa maisha ya wenyeji.",
    "improvement": "Ningependa chaguo la kundi dogo zaidi.",
    "original_favorite": "The experience felt authentic rather than touristy.",
    "original_improvement": "I would love an option for an even smaller group.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-12-19",
    "favorite": "Nilifurahia kukutana na wasanii wa eneo hilo sokoni.",
    "improvement": "Sauti ya mfumo wa sauti ingeweza kuongezwa.",
    "original_favorite": "I enjoyed meeting local artists at the market.",
    "original_improvement": "The audio system could be louder.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-12-21",
    "favorite": "Mwongoza watalii alijibu kila swali kwa uvumilivu.",
    "improvement": "Hakuna jambo kubwa linalohitaji kuboreshwa.",
    "original_favorite": "The guide answered every question with patience.",
    "original_improvement": "Nothing major needs improvement.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-12-23",
    "favorite": "Sehemu za kusimama kupiga picha zilichaguliwa vizuri sana.",
    "improvement": "Ziara ingeweza kutoa huduma ya mpiga picha mtaalamu.",
    "original_favorite": "The photography stops were perfectly chosen.",
    "original_improvement": "The tour could offer a professional photography option.",
    "is_demo": true
  },
  {
    "rating": 4,
    "language": "sw",
    "date": "2026-12-25",
    "favorite": "Bustani ya mimea ilikuwa na aina nyingi za mimea ya kuvutia.",
    "improvement": "Majina ya mimea yangeweza kuonyeshwa kwa uwazi zaidi.",
    "original_favorite": "The botanical garden had an amazing variety of plants.",
    "original_improvement": "The plant names could be displayed more clearly.",
    "is_demo": true
  },
  {
    "rating": 5,
    "language": "sw",
    "date": "2026-12-27",
    "favorite": "Wanajamii walikuwa wakarimu na wenye ukarimu kwa wageni.",
    "improvement": "Ningefurahia mazungumzo marefu zaidi na wenyeji.",
    "original_favorite": "The community members were generous and welcoming.",
    "original_improvement": "I would enjoy a longer conversation with the hosts.",
    "is_demo": true
  },
  {
    "rating": 3,
    "language": "sw",
    "date": "2026-12-02",
    "favorite": "Safari ya mashua ilitupa mandhari tofauti ya jiji.",
    "improvement": "Injini ya mashua ilikuwa na kelele wakati maelezo yalipotolewa.",
    "original_favorite": "The boat ride offered a different view of the city.",
    "original_improvement": "The boat engine was noisy during the explanations.",
    "is_demo": true
  }
];
