"""Curated fictional visitor voices for Noor's coffee farm; no Yelp text."""
FAVORITES = {
    "guide_quality": [
        "Noor welcomed us at the gate and made us feel at home.",
        "Our guide Noor explained things clearly without talking down to us.",
        "Noor is a knowledgeable host. She answered my son's questions patiently.",
        "Meeting the farm owner was the highlight; Noor was warm and funny.",
        "Our host remembered everyone's questions and made the visit personal.",
        "Noor was a great guide, especially when we asked about her family's farm.",
    ],
    "coffee_education": [
        "Noor showed us ripe coffee cherries beside the ones that still needed time.",
        "I finally understand why coffee cherries are picked by hand. Noor explained it well.",
        "Seeing the drying beds made the processing stages much easier to understand.",
        "Our guide let us compare coffee cherries at different stages of ripeness.",
        "Learning about harvesting and drying changed how I think about my morning cup.",
        "Noor explained coffee growing with examples from the plants right beside us.",
        "I liked following the beans from harvesting through processing, rather than just hearing a talk.",
    ],
    "coffee_roasting": [
        "The roasting demonstration smelled incredible.",
        "Noor let us watch the beans change colour during roasting.",
        "Hearing the first crack while roasting was my favourite moment.",
        "Our host explained how a few extra moments in the roaster change the flavour.",
        "Watching Noor roast a small batch was much more interesting than I expected.",
        "I enjoyed comparing the beans before and after roasting.",
        "Roasting coffee on the farm where it grew made the whole process click for me.",
    ],
    "coffee_tasting": [
        "The coffee tasting was excellent, especially the lighter cup.",
        "Fresh coffee with Noor at the end of the walk. Lovely.",
        "Our host helped us notice the differences between the coffee samples.",
        "I usually add sugar, but the brewed coffee here was delicious on its own.",
        "Noor's tasting changed my mind about black coffee.",
        "The coffee tasting gave us a good reason to slow down and compare flavours.",
        "Trying freshly brewed coffee from the plants we had just seen was special.",
        "I loved the tasting. Noor explained the flavours in ordinary words.",
    ],
    "farm_tour_content": [
        "Walking between the coffee plants was the best part of Noor's farm tour.",
        "The farm visit felt authentic, with everyday work happening around us.",
        "I liked the farm walk because we could actually see the coffee plants up close.",
        "Noor's coffee rows were a peaceful change from the town.",
        "This farm tour connected the plants, the people and the finished cup.",
        "Our host showed us a working farm, which was exactly what I hoped for.",
    ],
    "tour_difficulty": [
        "Noor offered us a shorter route, which suited my knees perfectly.",
        "The farm path was easier to manage than I expected.",
        "Our guide let us choose the gentler farm walk. I appreciated that.",
        "Noor explained the walking conditions before we set off.",
    ],
    "timing_pacing": [
        "The pacing felt relaxed. Noor never hurried our questions.",
        "The tour duration was about right for our family.",
        "Our guide balanced walking and demonstrations well.",
        "Noor gave us enough time to look around each part of the farm.",
    ],
    "group_size": [
        "The small group made it easy to ask Noor questions.",
        "I liked visiting with a small group rather than feeling lost in a crowd.",
        "Noor's small group tour felt like being invited onto a friend's farm.",
        "Our group size was comfortable and everyone got a turn to speak.",
    ],
    "facilities": [
        "The restroom was clean and easy to find after the farm walk.",
        "Noor's team kept the visitor area tidy.",
        "The benches near the demonstration area were comfortable.",
        "The water station was useful after walking around the coffee plants.",
    ],
    "transportation": [
        "The pickup to Noor's farm arrived when we were told it would.",
        "Parking at the farm was straightforward.",
        "Our ride to the farm was well organised by Noor's team.",
        "Noor helped us arrange transport back after the visit.",
    ],
    "accessibility": [
        "Noor checked what my mother could manage and offered an accessible route.",
        "The shaded rest stop was lovely after the farm walk.",
        "I appreciated the step-free option near the demonstration area.",
        "Our host made sure we knew about the easier route before arriving.",
    ],
    "price_value": [
        "Good value for a personal visit to Noor's working coffee farm.",
        "The price included more demonstrations than I expected.",
        "I thought the farm tour was worth the cost.",
        "Noor was clear about the price before we booked.",
    ],
    "staff_service": [
        "The farm staff were friendly and helped us settle in.",
        "Noor's helper was patient when our children needed a break.",
        "The team made us feel welcome from the moment we arrived.",
        "Helpful staff and a personal welcome from Noor.",
    ],
    "souvenirs": [
        "Finding coffee beans for sale after the tour was a lovely bonus.",
        "Noor helped me choose a small bag to take home.",
        "The local products were a nice reminder of the farm visit.",
        "I liked that the souvenirs had a clear connection to Noor's farm.",
    ],
    "information_signage": [
        "The directions Noor sent made the last turn easy to find.",
        "Clear signs helped us reach the farm without calling anyone.",
        "The arrival information explained which shoes to bring.",
        "Noor's map was simple and useful.",
    ],
    "scenery": [
        "The views over Noor's coffee farm were beautiful.",
        "Green coffee rows, birds and a quiet morning. That was my favourite part.",
        "I loved the farm scenery and the hills behind the plants.",
        "Our host gave us a moment to enjoy the landscape before heading back.",
        "The view from the coffee rows was worth stopping for.",
    ],
    "local_culture": [
        "Noor's family stories made the farm feel like more than a place to buy coffee.",
        "I enjoyed learning how coffee fits into the local culture.",
        "The farm owner spoke warmly about the community around the farm.",
        "Our guide shared coffee traditions I had never heard about.",
        "Noor's farm stories were the part I kept thinking about afterwards.",
    ],
}

PERSONAL_NOTES = [
    "Noor made us feel welcome.", "I could have listened to Noor for longer.",
    "My partner enjoyed meeting Noor too.", "Noor had a lovely sense of humour.",
    "It was nice to meet Noor in person.", "Noor remembered the question I asked at the gate.",
    "We left with a much better picture of Noor's everyday work.",
    "Our host made time for us even when we stayed a little behind.",
    "Noor gave a thoughtful answer to my last question.",
    "I am glad we made time for Noor's farm on our trip.",
    "Our guide was easy to talk to.", "Noor clearly cares about what she does.",
    "My teenager was surprisingly interested in Noor's explanation.",
    "We talked about Noor's farm all the way back.",
    "Noor's welcome was personal and unhurried.",
    "Our host made a first-time farm visitor feel comfortable.",
    "It was a good way to spend the morning at Noor's farm.",
    "I would bring my family to meet Noor next time.",
    "Noor was happy to explain it a second time.",
    "This was my first visit to a coffee farm.",
]

IMPROVEMENTS = {
    "coffee_tasting": [
        "There was not enough time for the coffee tasting.",
        "The tasting felt rushed; a few extra minutes would help.",
        "Not enough time to compare the coffee samples properly.",
        "The coffee tasting was too rushed for me to ask about the flavours.",
        "I found the tasting rushed after such an interesting farm visit.",
        "There was not enough time to taste the second cup slowly.",
        "The coffee samples came quickly and the tasting felt rushed.",
        "The tasting was rushed. I would have liked a calmer finish.",
    ],
    "group_size": [
        "The large group made it difficult to hear Noor at the roasting area.",
        "Our larger group was too noisy to hear Noor explain the farm.",
        "The group size made it hard to hear Noor from the back.",
        "It was difficult to hear Noor clearly with a large group around the plants.",
    ],
    "facilities": [
        "Please add seating near the roasting demonstration.",
        "We need a little more seating for older visitors at the end of the walk.",
    ],
    "information_signage": [
        "The directions were difficult to follow at the final turn to Noor's farm.",
        "Finding the gate was hard because the farm signs were unclear.",
        "The map was difficult to use near the last junction.",
        "The directions were poor once we left the main road.",
        "The farm signage was difficult to spot from our car.",
        "The arrival instructions made the final turn hard to find.",
    ],
    "tour_difficulty": [
        "The path was too steep for my father.",
        "The farm walk was tiring after the rain.",
        "The path was slippery in places and I struggled to keep up.",
        "The climb back from the coffee rows was difficult for me.",
        "The muddy path was hard to walk on in our shoes.",
        "The uphill section was too steep for our youngest child.",
        "The walk back was tiring in the afternoon heat.",
    ],
    "coffee_roasting": [
        "There was not enough time to watch the roasting closely.",
        "The roasting demonstration felt rushed at the end.",
        "More time to see the roast change would be useful.",
        "I wish we could watch the roasting for a few extra minutes.",
        "Please allow a little longer for questions about roasting.",
    ],
    "souvenirs": [
        "Please offer small bags of beans to take home.",
        "I wanted to buy coffee after the visit but could not see where to do that.",
        "I wish there were more local products available at the farm.",
        "Please make it clearer which coffee beans are for sale.",
        "I would love a small souvenir from Noor's farm.",
    ],
    "accessibility": [
        "Please offer more shade along the sunny part of the walk.",
        "I wish the rest stop had shade in the afternoon.",
        "We need clearer accessibility details before booking with someone using a wheelchair.",
        "Please explain which parts of the farm are step-free before we arrive.",
    ],
    "timing_pacing": [
        "The pacing felt rushed at the busiest stops.",
        "Please say how long the tour lasts before we arrive.",
        "I wanted a longer tour with more time for questions.",
        "The tour duration was too long for our children.",
        "More time to ask Noor questions would be helpful.",
    ],
    "transportation": [
        "Please explain the pickup time more clearly.",
        "The parking information was difficult to find before our visit.",
        "Our transport arrived late and we missed the start.",
    ],
    "price_value": [
        "The price felt a bit expensive for the time we had on the farm.",
        "Please explain what the tour price includes before booking.",
        "I was unsure about the cost of the optional tasting.",
    ],
}
